<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');

?>
<main id="anchor-content" class="page-content"><div id="page:main-container" class="page-columns"><div class="admin__old"><div id="container" class="main-col">

        <form action="<?php echo $this->getUrl('Codilar_Csvupload/csvupload/generate'); ?>" method="post" id="csv_upload" name="csv_upload" enctype="multipart/form-data">
                    <?php echo $block->getBlockHtml('formkey')?>
                    
                    <table class="data-grid" id="sales_transactions_grid_table">
                    <!-- Rendering column set -->
                    <thead>
                    <tr>
                         <th class="data-grid-th   col-period last col-created_at"><span>Services Upload Through CSV</span></th>
                    </tr>
                    <tr class="data-grid-filters" data-role="filter-form">
                        <td data-column="created_at" class="col-period last col-created_at">
                            <div class="field overview required" data-role="filter-form" id="date_range">
                     <span class="field-row">
                         <label for="date_from">
                            <span><?php echo __('Select CSV file to upload') ?>:</span>
                         </label>
                         <input size="25" class="input-text required-entry admin__control-text required-entry _required"
                                type="file"
                                id="csvfile"
                                name="csvfile"
                         />

                           <span id="date_from_advice"></span>
                       </span>

                                            </div>
                        </td>
                    </tr>
                    </thead>

                    <tbody>

                    <tr class="data-grid-tr-no-data even" data-role="row">
                        <td class="empty-text" colspan="8">
                            <button type="reset">Reset</button>
                            <button  data-bind="" id="upload-csv" class="action primary">Submit</button>
                    </tr>
                    </tbody>

                </table>
</form>

            </div></div></div>
<div style="background-color: lightgrey">
</div>

</main>

<script>
    require([
        'jquery',
        'mage/mage'
    ], function($){


        $( "#upload-csvffff" ).click(function() {
            event.preventDefault();

            var fd = new FormData();
            var formSubmit = '<?php echo $this->getUrl('Codilar_Csvupload/csvupload/generate'); ?>';
            fd.append( "fileInput", $("#csvfile")[0].files[0]);
            $.ajax({
                url: formSubmit,
                showLoader : true,
                data:{file:fd},
                success: function(data) {
                  //  document.location.href = Url +'commissionReports/'+data ;

                }
            });





        });




    });
</script>





