<main id="anchor-content" class="page-content"><div id="page:main-container" class="page-columns"><div class="admin__old"><div id="container" class="main-col">

                <form action="" method="" id="" name="" enctype="multipart/form-data">
                    <?php echo $block->getBlockHtml('formkey')?>

                    <table class="data-grid" id="sales_transactions_grid_table">
                        <!-- Rendering column set -->
                        <thead>
                        <tr>
                            <th class="data-grid-th   col-period last col-created_at"><span>Google Analytics Multiple Views</span></th>
                        </tr>

                        </thead>

                        <tbody>

                        <tr class="data-grid-tr-no-data even" data-role="row">
                            <td class="empty-text" colspan="12">
                                <div id="embed-api-auth-container1"></div>
                                <div id="chart-1-container"></div>
                                <div id="view-selector-1-container"></div>
                                <div id="chart-2-container"></div>
                                <div id="view-selector-2-container"></div>
                            </td>
                        </tr>
                        </tbody>

                    </table>


                </form>

            </div></div></div>
    <div style="background-color: lightgrey">
    </div>

</main>

<script>
    (function(w,d,s,g,js,fs){
        g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(f){this.q.push(f);}};
        js=d.createElement(s);fs=d.getElementsByTagName(s)[0];
        js.src='https://apis.google.com/js/platform.js';
        fs.parentNode.insertBefore(js,fs);js.onload=function(){g.load('analytics');};
    }(window,document,'script'));

</script>

<!--Embed API Multiple Views-->
<script>

    gapi.analytics.ready(function() {

        /**
         * Authorize the user immediately if the user has already granted access.
         * If no access has been created, render an authorize button inside the
         * element with the ID "embed-api-auth-container".
         */
        gapi.analytics.auth.authorize({
            container: 'embed-api-auth-container1',
            clientid: '<?php echo $block->getClientId(); ?>'
        });


        /**
         * Create a ViewSelector for the first view to be rendered inside of an
         * element with the id "view-selector-1-container".
         */
        var viewSelector1 = new gapi.analytics.ViewSelector({
            container: 'view-selector-1-container'
        });

        /**
         * Create a ViewSelector for the second view to be rendered inside of an
         * element with the id "view-selector-2-container".
         */
        var viewSelector2 = new gapi.analytics.ViewSelector({
            container: 'view-selector-2-container'
        });

        // Render both view selectors to the page.
        viewSelector1.execute();
        viewSelector2.execute();


        /**
         * Create the first DataChart for top countries over the past 30 days.
         * It will be rendered inside an element with the id "chart-1-container".
         */
        var dataChart1 = new gapi.analytics.googleCharts.DataChart({
            query: {
                metrics: 'ga:sessions',
                dimensions: 'ga:country',
                'start-date': '30daysAgo',
                'end-date': 'yesterday',
                'max-results': 6,
                sort: '-ga:sessions'
            },
            chart: {
                container: 'chart-1-container',
                type: 'PIE',
                options: {
                    width: '100%',
                    pieHole: 4/9
                }
            }
        });


        /**
         * Create the second DataChart for top countries over the past 30 days.
         * It will be rendered inside an element with the id "chart-2-container".
         */
        var dataChart2 = new gapi.analytics.googleCharts.DataChart({
            query: {
                metrics: 'ga:sessions',
                dimensions: 'ga:country',
                'start-date': '30daysAgo',
                'end-date': 'yesterday',
                'max-results': 6,
                sort: '-ga:sessions'
            },
            chart: {
                container: 'chart-2-container',
                type: 'PIE',
                options: {
                    width: '100%',
                    pieHole: 4/9
                }
            }
        });

        /**
         * Update the first dataChart when the first view selecter is changed.
         */
        viewSelector1.on('change', function(ids) {
            dataChart1.set({query: {ids: ids}}).execute();
        });

        /**
         * Update the second dataChart when the second view selecter is changed.
         */
        viewSelector2.on('change', function(ids) {
            dataChart2.set({query: {ids: ids}}).execute();
        });

    });
</script>
