<?php



?>
<main id="anchor-content" class="page-content"><div id="page:main-container" class="page-columns"><div class="admin__old"><div id="container" class="main-col">

<form action="" method="" id="" name="" enctype="multipart/form-data">
<?php echo $block->getBlockHtml('formkey')?>

    <table class="data-grid" id="sales_transactions_grid_table">
    <!-- Rendering column set -->
        <thead>
        <tr>
             <th class="data-grid-th   col-period last col-created_at"><span>Google Analytics</span></th>
        </tr>

        </thead>

        <tbody>

            <tr class="data-grid-tr-no-data even" data-role="row">
                <td class="empty-text" colspan="12">
                    <div id="embed-api-auth-container"></div>
                    <div id="chart-container"></div>
                    <div id="view-selector-container"></div>
                </td>
            </tr>
        </tbody>

    </table>



</form>

            </div></div></div>
<div style="background-color: lightgrey">
</div>

</main>

<!--Embed API Single Views-->
    <script>
    /*single chart*/
    gapi.analytics.ready(function() {

     /**
     * Authorize the user immediately if the user has already granted access.
     * If no access has been created, render an authorize button inside the
     * element with the ID "embed-api-auth-container".
     */
     gapi.analytics.auth.authorize({
     container: 'embed-api-auth-container',
     clientid: "938526124221-appkmm3pd0n28rs1t4b4tam59lm3cq2n.apps.googleusercontent.com"
     });


     /**
     * Create a new ViewSelector instance to be rendered inside of an
     * element with the id "view-selector-container".
     */
     var viewSelector = new gapi.analytics.ViewSelector({
     container: 'view-selector-container'
     });

     // Render the view selector to the page.
     viewSelector.execute();


     /**
     * Create a new DataChart instance with the given query parameters
     * and Google chart options. It will be rendered inside an element
     * with the id "chart-container".
     */
     var dataChart = new gapi.analytics.googleCharts.DataChart({
     query: {
     metrics: 'ga:sessions',
     dimensions: 'ga:date',
     'start-date': '30daysAgo',
     'end-date': 'yesterday'
     },
     chart: {
     container: 'chart-container',
     type: 'LINE',
     options: {
     width: '100%'
     }
     }
     });


     /**
     * Render the dataChart on the page whenever a new view is selected.
     */
     viewSelector.on('change', function(ids) {
     dataChart.set({query: {ids: ids}}).execute();
     });

     });
</script>


<script>
    function getClientId() {
        return "938526124221-appkmm3pd0n28rs1t4b4tam59lm3cq2n.apps.googleusercontent.com";
    }
</script>






